[2024-05-25T19:10:06.453+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T19:10:06.473+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_catedra_airflow.first-step-el scheduled__2023-06-20T00:05:00+00:00 [queued]>
[2024-05-25T19:10:06.480+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_catedra_airflow.first-step-el scheduled__2023-06-20T00:05:00+00:00 [queued]>
[2024-05-25T19:10:06.480+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-25T19:10:06.491+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): first-step-el> on 2023-06-20 00:05:00+00:00
[2024-05-25T19:10:06.497+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=833) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T19:10:06.499+0000] {standard_task_runner.py:63} INFO - Started process 835 to run task
[2024-05-25T19:10:06.499+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_catedra_***', 'first-step-el', 'scheduled__2023-06-20T00:05:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_clase.py', '--cfg-path', '/tmp/tmpryeuy176']
[2024-05-25T19:10:06.500+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask first-step-el
[2024-05-25T19:10:06.538+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_catedra_airflow.first-step-el scheduled__2023-06-20T00:05:00+00:00 [running]> on host 328b16f677f9
[2024-05-25T19:10:06.622+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_catedra_***' AIRFLOW_CTX_TASK_ID='first-step-el' AIRFLOW_CTX_EXECUTION_DATE='2023-06-20T00:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-20T00:05:00+00:00'
[2024-05-25T19:10:06.624+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T19:10:06.625+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T19:10:06.626+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: step_ingesta_carga_pura() missing 1 required positional argument: 'password'
[2024-05-25T19:10:06.634+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=DAG_catedra_***, task_id=first-step-el, run_id=scheduled__2023-06-20T00:05:00+00:00, execution_date=20230620T000500, start_date=20240525T191006, end_date=20240525T191006
[2024-05-25T19:10:06.649+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task first-step-el (step_ingesta_carga_pura() missing 1 required positional argument: 'password'; 835)
[2024-05-25T19:10:06.672+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T19:10:06.695+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T19:10:06.707+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
